version: '3.8'

services:
  
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: encuestas
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongosecret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5002:5000"
    networks:
      - web
    depends_on:
      - db
      - mongodb
      - redis
    volumes:
      - .:/opt/app
    command: ./start.sh

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

  mongodb:
    image: mongo:3
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongosecret
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongosecret
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    networks:
      - web
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  mongodb-data: